"""add note fields to operator_logs

Revision ID: 4969e1ded59c
Revises: 
Create Date: 2025-09-28 03:34:33.487045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4969e1ded59c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('note_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('note_photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_logs', schema=None) as batch_op:
        batch_op.drop_column('note_photo_url')
        batch_op.drop_column('note_date')
        batch_op.drop_column('note_number')

    # ### end Alembic commands ###
