"""add warnings table and relations

Revision ID: a90c1c7715c2
Revises: 4969e1ded59c
Create Date: 2025-10-14 21:02:07.467956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90c1c7715c2'
down_revision = '4969e1ded59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('worker_name', sa.String(length=120), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('source_form', sa.String(length=20), nullable=True),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('attachment_mime', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warnings_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_warnings_level_created', ['level', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warnings', schema=None) as batch_op:
        batch_op.drop_index('ix_warnings_level_created')
        batch_op.drop_index(batch_op.f('ix_warnings_created_at'))

    op.drop_table('warnings')
    # ### end Alembic commands ###
